name: deployment
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "mi-rama-personal" ]

# Environment variables definition.
env:
  # gets the secret and assign them to a local variable
  MI_VARIABLE: ${{ secrets.MI_TOKEN_DE_ACCESO }} 
  
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Deploy Application
        run: |
          echo "El contenido de mi variable es $MI_VARIABLE"
